<?php

return [
    [
        'MA_CHUC_NANG_CODE' => 'dashboard',
        'TEN_CHUC_NANG' => 'Tổng quan',
        'PAGE' => 'dashboard',
        'MODULE' => 'Tổng quan',
        'ICON' => 'dashboard',
        'THU_TU' => 100,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_khoa',
        'TEN_CHUC_NANG' => 'Tạo khoa/bộ môn',
        'PAGE' => 'create_khoa',
        'MODULE' => 'Quản lý khoa/bộ môn',
        'ICON' => 'department',
        'THU_TU' => 201,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_departments',
        'TEN_CHUC_NANG' => 'Danh sách khoa/bộ môn',
        'PAGE' => 'list_departments',
        'MODULE' => 'Quản lý khoa/bộ môn',
        'ICON' => 'department',
        'THU_TU' => 202,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
        'MENU_PAGE' => 'list_khoa',
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_khoa',
        'TEN_CHUC_NANG' => 'Chỉnh sửa khoa/bộ môn',
        'PAGE' => 'edit_khoa',
        'MODULE' => 'Quản lý khoa/bộ môn',
        'ICON' => 'department',
        'THU_TU' => 203,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_khoa',
        'TEN_CHUC_NANG' => 'Xóa khoa/bộ môn',
        'PAGE' => 'delete_khoa',
        'MODULE' => 'Quản lý khoa/bộ môn',
        'ICON' => 'department',
        'THU_TU' => 204,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_major',
        'TEN_CHUC_NANG' => 'Tạo ngành học',
        'PAGE' => 'create_major',
        'MODULE' => 'Quản lý ngành học',
        'ICON' => 'major',
        'THU_TU' => 301,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_majors',
        'TEN_CHUC_NANG' => 'Danh sách ngành học',
        'PAGE' => 'list_majors',
        'MODULE' => 'Quản lý ngành học',
        'ICON' => 'major',
        'THU_TU' => 302,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
        'MENU_PAGE' => 'list_major',
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_major',
        'TEN_CHUC_NANG' => 'Chỉnh sửa ngành học',
        'PAGE' => 'edit_major',
        'MODULE' => 'Quản lý ngành học',
        'ICON' => 'major',
        'THU_TU' => 303,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_major',
        'TEN_CHUC_NANG' => 'Xóa ngành học',
        'PAGE' => 'delete_major',
        'MODULE' => 'Quản lý ngành học',
        'ICON' => 'major',
        'THU_TU' => 304,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'change_status_major',
        'TEN_CHUC_NANG' => 'Đổi trạng thái ngành học',
        'PAGE' => 'change_status_major',
        'MODULE' => 'Quản lý ngành học',
        'ICON' => 'major',
        'THU_TU' => 305,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_class',
        'TEN_CHUC_NANG' => 'Tạo lớp học',
        'PAGE' => 'create_class',
        'MODULE' => 'Quản lý lớp',
        'ICON' => 'class',
        'THU_TU' => 401,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_classes',
        'TEN_CHUC_NANG' => 'Danh sách lớp học',
        'PAGE' => 'list_classes',
        'MODULE' => 'Quản lý lớp',
        'ICON' => 'class',
        'THU_TU' => 402,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
        'MENU_PAGE' => 'list_class',
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_class',
        'TEN_CHUC_NANG' => 'Chỉnh sửa lớp học',
        'PAGE' => 'edit_class',
        'MODULE' => 'Quản lý lớp',
        'ICON' => 'class',
        'THU_TU' => 403,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_class',
        'TEN_CHUC_NANG' => 'Xóa lớp học',
        'PAGE' => 'delete_class',
        'MODULE' => 'Quản lý lớp',
        'ICON' => 'class',
        'THU_TU' => 404,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'change_status_class',
        'TEN_CHUC_NANG' => 'Đổi trạng thái lớp học',
        'PAGE' => 'change_status_class',
        'MODULE' => 'Quản lý lớp',
        'ICON' => 'class',
        'THU_TU' => 405,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_year',
        'TEN_CHUC_NANG' => 'Tạo niên khóa',
        'PAGE' => 'create_year',
        'MODULE' => 'Quản lý niên khóa',
        'ICON' => 'year',
        'THU_TU' => 501,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_academic_years',
        'TEN_CHUC_NANG' => 'Danh sách niên khóa',
        'PAGE' => 'list_academic_years',
        'MODULE' => 'Quản lý niên khóa',
        'ICON' => 'year',
        'THU_TU' => 502,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
        'MENU_PAGE' => 'list_year',
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_year',
        'TEN_CHUC_NANG' => 'Chỉnh sửa niên khóa',
        'PAGE' => 'edit_year',
        'MODULE' => 'Quản lý niên khóa',
        'ICON' => 'year',
        'THU_TU' => 503,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_year',
        'TEN_CHUC_NANG' => 'Xóa niên khóa',
        'PAGE' => 'delete_year',
        'MODULE' => 'Quản lý niên khóa',
        'ICON' => 'year',
        'THU_TU' => 504,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'change_status_year',
        'TEN_CHUC_NANG' => 'Đổi trạng thái niên khóa',
        'PAGE' => 'change_status_year',
        'MODULE' => 'Quản lý niên khóa',
        'ICON' => 'year',
        'THU_TU' => 505,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_semester',
        'TEN_CHUC_NANG' => 'Tạo học kỳ',
        'PAGE' => 'create_semester',
        'MODULE' => 'Quản lý học kỳ',
        'ICON' => 'semester',
        'THU_TU' => 601,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_semester',
        'TEN_CHUC_NANG' => 'Danh sách học kỳ',
        'PAGE' => 'list_semester',
        'MODULE' => 'Quản lý học kỳ',
        'ICON' => 'semester',
        'THU_TU' => 602,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_semester',
        'TEN_CHUC_NANG' => 'Chỉnh sửa học kỳ',
        'PAGE' => 'edit_semester',
        'MODULE' => 'Quản lý học kỳ',
        'ICON' => 'semester',
        'THU_TU' => 603,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_semester',
        'TEN_CHUC_NANG' => 'Xóa học kỳ',
        'PAGE' => 'delete_semester',
        'MODULE' => 'Quản lý học kỳ',
        'ICON' => 'semester',
        'THU_TU' => 604,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'change_status_semester',
        'TEN_CHUC_NANG' => 'Đổi trạng thái học kỳ',
        'PAGE' => 'change_status_semester',
        'MODULE' => 'Quản lý học kỳ',
        'ICON' => 'semester',
        'THU_TU' => 605,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_student',
        'TEN_CHUC_NANG' => 'Cấp tài khoản sinh viên',
        'PAGE' => 'create_student',
        'MODULE' => 'Quản lý sinh viên',
        'ICON' => 'student',
        'THU_TU' => 701,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_students',
        'TEN_CHUC_NANG' => 'Danh sách sinh viên',
        'PAGE' => 'list_students',
        'MODULE' => 'Quản lý sinh viên',
        'ICON' => 'student',
        'THU_TU' => 702,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_student',
        'TEN_CHUC_NANG' => 'Chỉnh sửa sinh viên',
        'PAGE' => 'edit_student',
        'MODULE' => 'Quản lý sinh viên',
        'ICON' => 'student',
        'THU_TU' => 703,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_student',
        'TEN_CHUC_NANG' => 'Xóa sinh viên',
        'PAGE' => 'delete_student',
        'MODULE' => 'Quản lý sinh viên',
        'ICON' => 'student',
        'THU_TU' => 704,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'change_status_student',
        'TEN_CHUC_NANG' => 'Đổi trạng thái sinh viên',
        'PAGE' => 'change_status_student',
        'MODULE' => 'Quản lý sinh viên',
        'ICON' => 'student',
        'THU_TU' => 705,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_account',
        'TEN_CHUC_NANG' => 'Cấp tài khoản',
        'PAGE' => 'create_account',
        'MODULE' => 'Quản lý tài khoản',
        'ICON' => 'account',
        'THU_TU' => 801,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_accounts',
        'TEN_CHUC_NANG' => 'Danh sách tài khoản',
        'PAGE' => 'list_accounts',
        'MODULE' => 'Quản lý tài khoản',
        'ICON' => 'account',
        'THU_TU' => 802,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_account',
        'TEN_CHUC_NANG' => 'Chỉnh sửa tài khoản',
        'PAGE' => 'edit_account',
        'MODULE' => 'Quản lý tài khoản',
        'ICON' => 'account',
        'THU_TU' => 803,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_account',
        'TEN_CHUC_NANG' => 'Xóa tài khoản',
        'PAGE' => 'delete_account',
        'MODULE' => 'Quản lý tài khoản',
        'ICON' => 'account',
        'THU_TU' => 804,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'change_status_account',
        'TEN_CHUC_NANG' => 'Đổi trạng thái tài khoản',
        'PAGE' => 'change_status_account',
        'MODULE' => 'Quản lý tài khoản',
        'ICON' => 'account',
        'THU_TU' => 805,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'approve_account',
        'TEN_CHUC_NANG' => 'Duyệt tài khoản',
        'PAGE' => 'approve_account',
        'MODULE' => 'Quản lý tài khoản',
        'ICON' => 'account',
        'THU_TU' => 806,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'reject_account',
        'TEN_CHUC_NANG' => 'Từ chối tài khoản',
        'PAGE' => 'reject_account',
        'MODULE' => 'Quản lý tài khoản',
        'ICON' => 'account',
        'THU_TU' => 807,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'role_permission',
        'TEN_CHUC_NANG' => 'Cấp quyền truy cập',
        'PAGE' => 'role_permission',
        'MODULE' => 'Quản lý phân quyền',
        'ICON' => 'permission',
        'THU_TU' => 901,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
        'MENU_PAGE' => 'roles',
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_role_permissions',
        'TEN_CHUC_NANG' => 'Danh sách phân quyền',
        'PAGE' => 'list_role_permissions',
        'MODULE' => 'Quản lý phân quyền',
        'ICON' => 'permission',
        'THU_TU' => 902,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'register_permissions',
        'TEN_CHUC_NANG' => 'Đăng ký chức năng',
        'PAGE' => 'register_permissions',
        'MODULE' => 'Quản lý phân quyền',
        'ICON' => 'permission',
        'THU_TU' => 903,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'setup_criteria',
        'TEN_CHUC_NANG' => 'Thiết lập bộ tiêu chí',
        'PAGE' => 'setup_criteria',
        'MODULE' => 'Quản lý tiêu chí điểm',
        'ICON' => 'criteria',
        'THU_TU' => 1001,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'apply_criteria',
        'TEN_CHUC_NANG' => 'Áp dụng bộ tiêu chí',
        'PAGE' => 'apply_criteria',
        'MODULE' => 'Quản lý tiêu chí điểm',
        'ICON' => 'criteria',
        'THU_TU' => 1002,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_criteria',
        'TEN_CHUC_NANG' => 'Danh sách tiêu chí',
        'PAGE' => 'list_criteria',
        'MODULE' => 'Quản lý tiêu chí điểm',
        'ICON' => 'criteria',
        'THU_TU' => 1003,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'configure_criteria',
        'TEN_CHUC_NANG' => 'Cấu hình tiêu chí',
        'PAGE' => 'configure_criteria',
        'MODULE' => 'Quản lý tiêu chí điểm',
        'ICON' => 'criteria',
        'THU_TU' => 1004,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_criteria',
        'TEN_CHUC_NANG' => 'Tạo tiêu chí',
        'PAGE' => 'create_criteria',
        'MODULE' => 'Quản lý tiêu chí điểm',
        'ICON' => 'criteria',
        'THU_TU' => 1005,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_criteria',
        'TEN_CHUC_NANG' => 'Chỉnh sửa tiêu chí',
        'PAGE' => 'edit_criteria',
        'MODULE' => 'Quản lý tiêu chí điểm',
        'ICON' => 'criteria',
        'THU_TU' => 1006,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'create_activity',
        'TEN_CHUC_NANG' => 'Tạo hoạt động',
        'PAGE' => 'create_activity',
        'MODULE' => 'Quản lý hoạt động',
        'ICON' => 'activity',
        'THU_TU' => 1101,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_activities',
        'TEN_CHUC_NANG' => 'Danh sách hoạt động',
        'PAGE' => 'list_activities',
        'MODULE' => 'Quản lý hoạt động',
        'ICON' => 'activity',
        'THU_TU' => 1102,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
        'MENU_PAGE' => 'list_activity',
    ],
    [
        'MA_CHUC_NANG_CODE' => 'edit_activity',
        'TEN_CHUC_NANG' => 'Chỉnh sửa hoạt động',
        'PAGE' => 'edit_activity',
        'MODULE' => 'Quản lý hoạt động',
        'ICON' => 'activity',
        'THU_TU' => 1103,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'delete_activity',
        'TEN_CHUC_NANG' => 'Xóa hoạt động',
        'PAGE' => 'delete_activity',
        'MODULE' => 'Quản lý hoạt động',
        'ICON' => 'activity',
        'THU_TU' => 1104,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'change_status_activity',
        'TEN_CHUC_NANG' => 'Đổi trạng thái hoạt động',
        'PAGE' => 'change_status_activity',
        'MODULE' => 'Quản lý hoạt động',
        'ICON' => 'activity',
        'THU_TU' => 1105,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'approve_activity',
        'TEN_CHUC_NANG' => 'Duyệt hoạt động',
        'PAGE' => 'approve_activity',
        'MODULE' => 'Quản lý hoạt động',
        'ICON' => 'activity',
        'THU_TU' => 1106,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'reject_activity',
        'TEN_CHUC_NANG' => 'Từ chối hoạt động',
        'PAGE' => 'reject_activity',
        'MODULE' => 'Quản lý hoạt động',
        'ICON' => 'activity',
        'THU_TU' => 1107,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => false,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'list_evaluations',
        'TEN_CHUC_NANG' => 'Chấm điểm rèn luyện',
        'PAGE' => 'list_evaluations',
        'MODULE' => 'Quản lý đánh giá',
        'ICON' => 'evaluation',
        'THU_TU' => 1201,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
    [
        'MA_CHUC_NANG_CODE' => 'statistics',
        'TEN_CHUC_NANG' => 'Danh sách thống kê',
        'PAGE' => 'statistics',
        'MODULE' => 'Quản lý thống kê',
        'ICON' => 'statistics',
        'THU_TU' => 1301,
        'TRANG_THAI_CN' => 'HOAT_DONG',
        'HIEN_THI_MENU' => true,
    ],
];
